### PR TITLE
Exercise 2: Kids First Data Dashboard

### PR DESCRIPTION
**Pull request by dehall**
Work in progress of Exercise 2

This exercise will be a "fill-in-the-blanks" type exercise, with the intent of reinforcing the fundamentals of how to query for important FHIR resources as well as how to pick important fields out of those resources

### CODE REVIEW

**Comment by radamson** [comment]
Screen Shot 2022-01-11 at 2 19 02 PM

Can you add a link to the [US Core Race Extension](https://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-race.html) with some narrative. I think this is a good teachable moment that ties back into the spec:

Things to reinforce/talk about:
- What extensions are and how they appear in resources
- Choice Types (here the extension could be a String or Coding so we account for both.

Do we need to worry if multiple races/ethncities are listed for a specific patient? or should we be clear we're only looking at one?

**Comment by radamson** [comment]
Screen Shot 2022-01-11 at 2 32 42 PM

This is the start of a teachable moment for more specialized searches, could we add a simple chained search somewhere too? Maybe get all female patients with a specific condition?

A link to the search section and a link to the chained search section (https://hl7.org/fhir/r4/search.html#chaining) would be good since I think we'll want to pause and talk about what's going on here.

**Comment by radamson** [comment]
Screen Shot 2022-01-11 at 2 49 59 PM

Another teachable momeny as this is the first introduction of include/revIncludeso this will be another place to pause and talk about what's going on and why with at least some links to the spec for folks to learn more.

Also I remember you originally had a so-crazy-it-might-be-genius query for this originally (`Condition?subject._has:ResearchSubject:individual:study=76758`). I'm not even sure this type of query would really work with any server, but it might be another good teaching moment. Even better if we could find a really simple example of it working (even if on Logica) to demonstrate crazy things are sometimes possible, but won't always work.

**Comment by radamson** [comment]
Also, none of ☝️/👇  should be blockers to merging IMO if we'd prefer to put this in a follow on PR if it makes anyone's life easier review-wise.

**Comment by radamson** [comment]
Screen Shot 2022-01-11 at 3 05 10 PM

I like the use of join here. I wonder if we could use this to teach how there are multiple ways to do things and the importance of references tying resources together.

e.g.
* We could search for Conditions by Patient and then search for Observations by Patient and join together
* OR we could search for all at once using revIncludes
We can get the same result either way, but it really depends on your use case, how you want to design your queries, queries available, etc.

References are such a core part of FHIR and we should try and hammer that home (either here or in one of the other exercises)

**Review by jawalonoski — COMMENTED** [review]
- This exercise has no title in the Markdown.
- Resolve "TODO: Kids First uses MONDO codes". Link to the 
  - Monarch Initiative (https://monarchinitiative.org)
  - https://mondo.monarchinitiative.org
  - https://github.com/monarch-initiative/mondo
- BONUS if you put a copy of the image of the KidsFirst graph next to our graphs (or when they are supposed to create a similar graph so they know more-or-less what to expect)

**Comment by radamson** [comment]
Screen Shot 2022-01-24 at 10 54 11 AM

`What is this notebook` can be deleted since you have the Motivation/Purpose below. Also once I don't think the ⚡ icon is ever used so that can probably be remvoed (along with the `any required MITRE legalese...`

**Comment by radamson** [comment]
Can you add some README or wiki instructions for how to refresh the KF cookie?

**Comment by radamson** [comment]
I'm still a little wary of printing giant bundles in the notebooks. It makes reviewing the notebook in GitHub very difficult since the JSON isn't contained in a smaller scrollable window and it would make it more difficult for anyone that doesn't want to run the notebook themselves to read it this way. Also my local JupyterLab instance seems to inconsistently collapse the output into a scrollable cell.

Could we maybe comment out the final `bundle` so that its readable in GitHub, but can still be uncommented when running to see the whole thing? Or maybe just show the first 20 lines of the bundle?

Screen Shot 2022-01-27 at 11 51 28 AM

**Comment by radamson** [comment]
Screen Shot 2022-01-27 at 11 56 17 AM

We do this same query in exercise 1 so I think it should be marked as ✋ for a knowledge check.

Could this be a good place to have them try `_count` (assuming KF respects it)?

**Review by radamson — APPROVED** [review]
This looks great!

We'll still need to break this out into a fill in the blank and answer sheet version, but I'm happy with merging this if others are.

**Comment by dehall** [comment]
> Could this be a good place to have them try `_count` (assuming KF respects it)?

It certainly could but I used _count in a followup step, so I thought this first one would be as simple as possible. If anyone feels strongly I'll add it here as well and update the wording.

Agree with the other comments as well so I'm updating those now.

**Comment by radamson** [comment]
@jawalonoski or @lmlevine any other feedback on this? If not we should merge (IMO) and make any other changes in subsequent PRs based on walking through all the exercises together.

Still need the fill-in-the-blank version, but that can come after we have general agreement on the completed version.

**Comment by radamson** [comment]
Added `DataFrame.describe` to align with `skim` used in the R notebook

Screen Shot 2022-01-27 at 3 58 15 PM

**Comment by jawalonoski** [comment]
image
👍 This is very good, especially for posterity.

**Comment by jawalonoski** [comment]
image
This is an opportunity to have them fill in the query. :hand:

**Review by jawalonoski — APPROVED** [review]
I made a commit that repeats the learning objectives at the end, as a recap, similar to Exercise 1.

I approve this, but I do think you missed one opportunity for a :hand: that I commented on above.

**Pull request merged**
