### PR TITLE
Exercise 2 updates

### PR DESCRIPTION
**Pull request by dehall**
This PR makes a few changes to Exercise 2 based on prior feedback:

 - Updates a couple instances of "fill in the python function" to "fill in the blanks of the python function" where the blanks are just field names or sequences of field accesses, and there are clues and 🖐s
 - Included the KF image directly in the notebook
 - Added a new library `lifelines` to perform the survival analysis in the final step. This simplifies the logic a bit.
 - Migrated the cookie-loading approach from a file to reading directly from the github repo

### CODE REVIEW

**Comment by masnick** [comment]
When doing the R translation of the survival analysis, I noticed there are multiple Condition resources per `patientId` returned by that last search.

It looks like this is manifesting as multiple rows per `patientId` in `obs_conds_df`:

image

I don't believe this is resolved before the data go into the survival analysis, so you likely need to add a filter on `Condition.code` before merging the DataFrames.

Edit: it looks like taking the minimum non-null value per patient works in R.

```r
df_condition %>% 
  mutate(
    recorded_duration = as.numeric(recorded_duration)
  ) %>% 
  # Remove rows with null recorded duration
  filter(!is.na(recorded_duration_units)) %>%
  
  # Get the minimum recorded duration for each patient_id
  group_by(patient_id) %>% 
  summarize(
    min_recorded_duration_years = min(recorded_duration) / 365.25
  )
```

**Comment by dehall** [comment]
Yeah the same thing is true on the other queries that link Condition & Patient - there is often more than one Condition per Patient. If you look extra closely, there are even some Conditions that have verificationStatus refuted, or something along those lines that says "the patient DOESN'T have this condition". The other issue in terms of survival analysis is that not all the conditions are the same; I imagine it's not the most useful to combine different conditions that have different progression/treatment into one survivability curve.

I suspect participants won't be looking that closely so I would lean toward leaving it as-is, but if we can quickly & cleanly fix it then that's ok too. Just don't want Reece to have to explain a lot more detail.

**Comment by dehall** [comment]
@masnick Updated to only use one Condition per patient. The logic in Python was:
```python
conditions_df = conditions_df.drop_duplicates(subset=['patientId'], keep='first')
```

**Comment by radamson** [comment]
Screen Shot 2022-02-15 at 1 09 56 PM

I think filtering for the `text` subextension is a safer bet and better instructs how the FHIR spec should be interpreted here. The `text` subextension is required for both ethnicity and race so we can depend on it being there, while `Coding.display` is optional so even if `ValueCoding` is present that doesn't mean a `display` will be. Filtering by URL/identifier is one of the primary ways we work with FHIR resources.

**Comment by dehall** [comment]
@radamson Updated. It does make the exercise even simpler, which I don't love but maybe that's the level we need to be at

**Comment by radamson** [comment]
It might be worth breaking this into 2 code blocks so that its easier to tell if query was populated correctly:

Screen Shot 2022-02-16 at 9 51 41 AM

i.e. the first block would be
```python
r = s.get(f"{FHIR_SERVER}/Patient?_has:Condition:patient:code=MONDO:0021640")
bundle = r.json()
print_bundle(bundle)
```

(This is in section 1.2, there's a similar one in 1.3)

**Comment by radamson** [comment]
In section 2.1 can we add a 📘 link to [_count](https://www.hl7.org/fhir/search.html#count). By the time we get to this point attendees might have forgotten so it might be good to add as a hint.

**Comment by radamson** [comment]
Screen Shot 2022-02-16 at 10 06 25 AM

Can we add a 📘 link to the [FHIR Condition Resource](https://www.hl7.org/fhir/condition.html) here? I think it will be useful since we'll want to jump to that page and explain that the element `Condition.code` is of type CodeableConcept.

**Comment by radamson** [comment]
In Section 2.1

* Some of the ✋ can be removed for the lines of code no longer expected to be filled
* The solutions version does not show the solution for `FILLMEIN`
* Why is `elif 'text' in c:` nested in `if 'coding' in c:`? Should this be deleted and be the `FILLMEIN` solution outside this if?

Screen Shot 2022-02-16 at 10 12 01 AM

**Comment by radamson** [comment]
In Section 2.2 something that I want to double check to make sure it works:

Either `/Condition?subject._has:ResearchSubject:individual:study=76758` OR `/Condition?subject._has:ResearchSubject:study=76758:individual` would work right?

**Comment by radamson** [comment]
Section 3.1

Can we add a 📘 link to [JSON representation of primitive elements](http://www.hl7.org/fhir/json.html#primitive)

Screen Shot 2022-02-16 at 10 34 23 AM

**Comment by radamson** [comment]
Section 3.1

We've shown how to filter extensions based on URL previously in this exercise so I would continue that here for getting both the extension and its subextensions. The subextensions use a URL discriminator and `ElementDefinition.slicing.ordered` is not set to true so order isn't guaranteed. (`First pick out the actual extension` could also be a ✋ if we want. If we think its too hard we can leave it filled in as a hint for how to filter the subextensions)

Screen Shot 2022-02-16 at 10 38 03 AM

**Comment by radamson** [comment]
Section 4.1

I'm not sure we'll want to get into too much detail here on this, but it might be worth having a 📘 for [token search](https://www.hl7.org/fhir/search.html#token)

and some commented out code showing other ways we can search for it. i.e.:

`# r = s.get(f"{FHIR_SERVER}/Observation?code=http://snomed.info/sct|263493007&_count=1"`

Screen Shot 2022-02-16 at 10 52 27 AM

**Comment by dehall** [comment]
@radamson I think all feedback has been addressed

**Review by radamson — APPROVED** [review]
10/10

**Pull request merged**
