### PR TITLE
WIP: Further update to Exercise 3

### PR DESCRIPTION
**Pull request by jawalonoski**
Debugged formatting issue where drug codes output as lists, and successfully built dictionary of patients to prescriptions

However final list not properly parsing the way the CSV does. Need to debug

Also need help on maturing queries and different types of explorations.

### CODE REVIEW

**Comment by jawalonoski** [comment]
In testing this exercise, I get the following error in the console:

```
AttributeError: Can't get attribute 'process_files' on <module '__main__' (built-in)>
```

when running this block:

```python
df = process('fhir-data')
df.info()
```

I'm not sure how long it is supposed to take, but it is either infinite or it failed with that `AttributeError`.

Mac OS X. Python 3. Jupyter Notebook 6.4.0.

**Comment by jawalonoski** [comment]
If I manually stop the block, the remainder of the notebooks _seems_ to run.

**Comment by jawalonoski** [comment]
The FHIR query is fine, but you don't really need to `_include` the Patient resources if you aren't going to do anything with them.

 ```
"https://api.logicahealth.org/researchonfhir/open/MedicationRequest?_include=MedicationRequest:patient"
```

It _looks_ like `df = process('fhir-data')` is merging patient.name and other stuff into the data frame, but all those columns are `NaN` on the actual medication rows... so, I'm not sure why you're bothering to `_include` that data, unless you intend to pull out their name and display it in the `print` lines.

**Comment by dehall** [comment]
We'll have to be very careful before merging this because it's showing Exercise 1 as deleted. We may want to revert that bit and squash rebase this to ensure we don't have any commits that delete things

**Review by jawalonoski — COMMENTED** [review]
- Remove all "DOD" or "DoD" acronyms, you can just write "Drug Interactions" (Drug on Drug is implied).
- Step 1 "Query all active prescriptions" isn't actually specifying the medications are active
- Step 3 goes before Step 2? There are two "Step 3" headings, one before, one after "Step 2"
- Step 2 - shorten the description or break it down.
- Step 4 just prints out interaction or not, therer is no "determination of aggregate risk". Is that a step for the student?

**Review by lmlevine — APPROVED** [review]

**Comment by dehall** [comment]
A couple notes:

- Exercises 1 and 2 use a requests.Session to ensure common headers, and define a constant for the FHIR server base URL, I'd suggest using the same here for consistency:

```python
FHIR_SERVER = 'https://kf-api-fhir-service.kidsfirstdrc.org'

# We make a requests.Session to ensure consistent headers/cookie across all the requests we make
s = requests.Session()
s.headers.update({'Accept': 'application/fhir+json'})
# disable SSL verification:
# these 2 lines should be commented out unless you actually see certificate errors
s.verify = False
requests.packages.urllib3.disable_warnings()
```

Then to make a call:
```python
r = s.get(f"{FHIR_SERVER}/Patient")
```



- The two example combinations in Step 2 are fine examples but they are just magic numbers. Can we add a little description of what they are and what we expect to see for each combination? (for example "lisinopril and hydrochlorothiazide are two commonly prescribed medications for blood pressure, which are often prescribed in combination. we expect the API to report no interactions" and "aspirin and warfarin both prevent blood clots but the combination may excessively increase bleeding. we expect the API to report an interaction" -- and to be clear those are not the codes used in the example but this is the kind of intro text I think would be useful)

**Comment by jawalonoski** [comment]
I've made some narrative edits...

There is one remaining piece of narrative I would change, but I'm not sure what this is trying to say:
```
Let's now borrow the list mapping lambda function we deployed to map out our JSON file
(entering the entire bundle, and mapping by resource) 
```

**Pull request merged**
